GET http://localhost:3000/files

###

GET http://localhost:3000/files/File2

###

POST http://localhost:3000/files
Content-Type: application/json

{
    "filename": "File1",
    "context": [
        "This is Line1",
        "This is Line2",
        "This is Line3",
        "This is Line4"
    ]
}
###
DELETE http://localhost:3000/files/example.txt


###
PATCH http://localhost:3000/files/File2
Content-Type: application/json

{
    "filename": "File5",
    "context" : [
        "This is Line1",
        "This is Line2",
        "This is Line3",
        "This is Line4"
    ]
}